apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: localhost:5000/my-docker-image:tag # Attemped to use local docker registry
          command:
            - "celery"
            - "-A"
            - "backend.index.celery_app"
            - "worker"
            - "--loglevel=info"
          volumeMounts:
            - mountPath: /app
              name: app-volume
            - mountPath: /var/run/docker.sock
              name: docker-sock-volume
      volumes:
        - name: app-volume
          hostPath:
            path: YOUR-PATH # TODO
        - name: docker-sock-volume
          hostPath:
            path: /var/run/docker.sock
